---
abstract: 'read MATLAB MAT-File data'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-MATFile
no_index:
  directory:
    - t
    - inc
requires:
  IO::Uncompress::Gunzip: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/benkasminbullock/Data-MATFile/issues
  repository: https://github.com/benkasminbullock/Data-MATFile
version: 0.02
